### ISSUE TITLE
Cant find module SharedComponent

### ISSUE THREAD

**Issue by vlimag** [drgx/react-native-plus-web#10]
When I try to run the project on Android device, without haul (Haul raises an error about delta bundle that I cant find on the company's devices) it raises another error:

`error: bundling failed: Error: Unable to resolve module shared/components/SharedComponent from /home/vitor/Repositories/Components/pd/react-native-plus-web/packages/apps/index.js: The module ../shared/components/SharedComponent could not be found from /home/vitor/Repositories/Components/pd/react-native-plus-web/packages/apps/index.js.`

I am new to monorepos, lerna and stuff, but I think this is related to it.

Any sugestion to get this solved?

Cheers,

**Comment by drgx** [comment]
hi @vlimag , sorry for slow response
I think you should read this https://github.com/drgx/react-native-plus-web#for-running-android 
you need to disable delta to be enable run it on `haul` :) 
Hopefully its works
